export {PACKAGE_NAME} from './package-name.js'
export {getMotionValueUpdateSerialOperations} from './get-motion-value-update-serial-operations.js'
export {type MotionInfo} from './motion-info.js'
export {requestMotionPermissions} from './request-motion-permissions.js'
export {subscribeToAccelerationChanges} from './subscribe-to-acceleration-changes.js'
export {subscribeToOrientationChanges} from './subscribe-to-orientation-changes.js'
export {type SubscribeToMotionChangesParam} from './subscribe-to-motion-changes-param.js'
export {LinkName} from './link-name.js'